### ISSUE TITLE
Error.

### ISSUE THREAD

**Issue by cavidev** [adrianandrei-ca/pgunit#10]
I tried to run a test in my database, but I got the next output error message
![captura](https://user-images.githubusercontent.com/17894391/32421218-ae6e9a96-c25b-11e7-81eb-f271d6bbae80.PNG)
the error says - syntax error in or near «.» - I already re-checked my procedure and it does not contain an error. I do not know if it will be the library, it would be useful if I could see what it is. Thanks for the library is a good contribution.

**Comment by adrianandrei-ca** [comment]
Please run the test case individually and then see the full error.Adrian-------- Original Message --------Subject: [adrianandrei-ca/pgunit] Error. (#10)From: Carlos Villafuerte To: adrianandrei-ca/pgunit CC: Subscribed I tried to run a test in my database, but I got the next output error message

the error says - syntax error in or near «.» - I already re-checked my procedure and it does not contain an error. I do not know if it will be the library, it would be useful if I could see what it is. Thanks for the library is a good contribution.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/adrianandrei-ca/pgunit","title":"adrianandrei-ca/pgunit","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/adrianandrei-ca/pgunit"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Error. (#10)"}],"action":{"name":"View Issue","url":"https://github.com/adrianandrei-ca/pgunit/issues/10"}}}

**Comment by odrnk** [comment]
I have the same problem.
```sql
create or replace function test_case_user_create_1() returns void as $$
declare
  id BIGINT;
begin
  perform test_assertNotNull('user not created', 0);
end;
$$ language plpgsql;

select * from test_run_suite('user');
```
and the result I get:
```csv
"test_name";"successful";"failed";"errorneous";"error_message";"duration"
"test_case_user_create_1";f;f;t;"syntax error at or near "".""";"00:00:00.001"
```
Postgres 9.6.

**Comment by KOFlynn** [comment]
Hi @CarlosMarioV, @adrianandrei-ca  
Did you find a solution to this issue. I am having a similar problem. 
When executing all test cases or as a suite I receive a similar error message ...
![image](https://user-images.githubusercontent.com/6141875/36732434-b2d5b722-1bc5-11e8-8ce5-7243f0d2a2b4.png)

And when I execute the test case individually it runs successfully.
`select * from myschema.test_case_ut_test();`
![image](https://user-images.githubusercontent.com/6141875/36732559-fd3d5d7e-1bc5-11e8-9993-fbc8ef91f2f8.png)

For completeness here is the code in case I am doing something stupid ..
```sql
CREATE TABLE myschema.ut_test (
  id integer,
  name varchar(100)
  );

INSERT INTO myschema.ut_test (id,name)
VALUES(1, 'first_rec');

create or replace function myschema.test_case_ut_test() returns void as $$
declare
  v_id integer;
begin
  
  SELECT id 
  INTO v_id
  from myschema.ut_test
  WHERE id = 1;
  
  perform pgunit.test_assertNotNull('user not created', v_id);

end;
$$ language plpgsql;
```
As you can see, all objects are in `myschema` and pgunit has been created in the `pgunit` schema.


**EDIT - resolved**
Discovered the issue was I needed to create the dblink extension in the pgunit schema
```sql
CREATE EXTENSION dblink SCHEMA pgunit;
```

But then I ran into a much bigger issue!!
I am running a postgres instance on AWS RDS and Amazon will NOT allow permissions to connect to the `dblink_connect_u()` function. So this UT framework will not work with postgres on AWS RDS unfortunately :(

https://forums.aws.amazon.com/thread.jspa?threadID=152184

**Comment by cavidev** [comment]
Thanks https://github.com/KOFlynn and @https://github.com/adrianandrei-ca ... I see you comment, but I can't find a solution to this 😔, I use the library for other thinks, but in this case specific not... I will close the issue because it is very old, about a year ... Really I appreciate your efforts.
